### ISSUE TITLE
screenshots

### ISSUE THREAD

**Issue by klesun-misc** [klesun-misc/vue-template-typing#1]

**Comment by klesun-misc** [comment]
![image](https://user-images.githubusercontent.com/30558426/81400361-8b9f7980-9135-11ea-9f22-d85c1465392a.png)

**Comment by klesun-misc** [comment]
![image](https://user-images.githubusercontent.com/30558426/81400508-f355c480-9135-11ea-9a25-3b24d09fa0d6.png)

**Comment by klesun** [comment]
![image](https://user-images.githubusercontent.com/5202330/84546274-ae5f1800-ad09-11ea-8946-5a6b05c382e3.png)
